name=HybridFS
version=1.0.0
author=AlexGyver <alex@alexgyver.ru>
maintainer=AlexGyver <alex@alexgyver.ru>
sentence=Wrapper for esp8266/esp32 flash and SD card filesystem
paragraph=Wrapper for esp8266/esp32 flash and SD card filesystem
category=Storage
url=https://github.com/GyverLibs/HybridFS
architectures=esp8266,esp32